# Generated by Django 4.0.5 on 2022-07-02 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('created_at',)},
        ),
    ]
