# Generated by Django 4.0.5 on 2022-07-07 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_rename_created_at_post_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='created_at',
        ),
    ]
