# Generated by Django 4.0.2 on 2022-03-24 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_doctor_subject_subject_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assisstant',
            name='section',
        ),
        migrations.AddField(
            model_name='subject',
            name='assisstant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.assisstant'),
        ),
    ]
