# Generated by Django 4.0.2 on 2022-03-24 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_lab_assisstant_lecture_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='subject',
            field=models.ManyToManyField(related_name='dep_subject', to='api.Subject'),
        ),
        migrations.AlterField(
            model_name='lab',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_lab', to='api.subject'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_lec', to='api.doctor'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject_lecture', to='api.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_subjects', to='api.doctor'),
        ),
    ]
