# Generated by Django 4.0.2 on 2022-03-25 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_department_subject_alter_lab_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='doctor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_lec', to='api.doctor'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='material_lec',
            field=models.FileField(default='', upload_to='uploads/material/lecture'),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subject_lecture', to='api.subject'),
        ),
    ]
