# Generated by Django 4.0.2 on 2022-03-29 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_lecture_doctor_alter_lecture_material_lec_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lab',
            name='assisstant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assisstant_lab', to='api.assisstant'),
        ),
    ]
