# Generated by Django 4.0.2 on 2022-03-29 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_alter_lab_assisstant'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assisstant',
            new_name='Assistant',
        ),
        migrations.RemoveField(
            model_name='lab',
            name='assisstant',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='assisstant',
        ),
        migrations.AddField(
            model_name='subject',
            name='assistant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistant_subjects', to='api.assistant'),
        ),
    ]
