# Generated by Django 4.0.5 on 2022-07-21 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_grade_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizzes'),
        ),
    ]
